-- Seed: 3 sample puzzles from prototype
-- date_active values use CURRENT_DATE so they work whenever you run this.
-- Adjust issue_no / vol as appropriate for your launch date.

INSERT INTO puzzles (issue_no, vol, date_active, title, genre, difficulty, prompt, answer, answer_display, hints, solution_lede, solution_steps, input_type, input_config)
VALUES
(
  1, 1,
  CURRENT_DATE,
  'The midnight bridge',
  'logic',
  3,
  '["Four travelers reach a narrow bridge at night. They share one flashlight, and at most two may cross at a time. Whoever crosses must carry the flashlight, and a pair walks at the slower person''s pace.", "Their individual crossing times are 1, 2, 5, and 10 minutes.", "What is the minimum total time, in minutes, for all four to reach the other side?"]',
  '17',
  '17',
  '["The 10-minute walker is your bottleneck — try to pair them with someone else slow.", "After two cross, somebody has to walk back with the flashlight. That return trip is wasted time. Minimize it.", "The 1- and 2-minute walkers are cheap couriers. Cross them first to stash the flashlight on the far side."]',
  'The instinct is to always send the fastest person back with the flashlight. But that strategy costs you: you''re using your best courier for round trips. The key insight is to batch the two slowest walkers into a single crossing, paying that cost only once.

The optimal path hinges on getting the 1-minute walker to the far side first, so they can return cheap. Then batch the 5 and 10 together.',
  '[{"body": "Cross 1 and 2 together (2 min). Return with 1 (1 min). Elapsed: 3 min.", "elapsed_min": "3 min"}, {"body": "Cross 5 and 10 together (10 min). Return with 2 (2 min). Elapsed: 15 min.", "elapsed_min": "15 min"}, {"body": "Cross 1 and 2 together (2 min). All four are across. Total: 17 min.", "elapsed_min": "17 min"}]',
  'choice',
  '{"options": ["15", "17", "19", "21"]}'
),
(
  2, 1,
  CURRENT_DATE + 1,
  '25 horses, no clock',
  'quant',
  4,
  '["You have 25 horses and a track that holds exactly 5 horses per race. There is no stopwatch — each race only tells you the finishing order of those 5.", "Assume every horse runs at a fixed, distinct speed.", "What is the minimum number of races needed to determine the three fastest horses overall?"]',
  '7',
  '7',
  '["Five races of 5 horses partition all 25 and give you a within-group ranking.", "A 6th race of the five group winners reveals the fastest horse overall — and lets you eliminate horses whose group leader is slow.", "After race 6 only seven horses can still be in the top 3. A single race ranks them."]',
  'The trick is that you don''t need to rank all 25 — you only need the top 3. This lets you aggressively eliminate horses after each race using transitive logic.

After 5 qualifying races you have the ranking within each group. One championship race among group winners tells you the overall winner and collapses which horses can still contend for 2nd and 3rd.',
  '[{"body": "Run 5 races of 5 horses each. Label the winner of each race A1–E1, with A1 being fastest.", "elapsed_min": "Races 1–5"}, {"body": "Run a 6th race of all 5 group winners. The winner (call them A1) is the fastest horse overall.", "elapsed_min": "Race 6"}, {"body": "The only horses that can be 2nd or 3rd: A2, A3 (A1''s groupmates), B1, B2 (2nd-place group winner + their groupmate), and C1. Run these 5 in race 7.", "elapsed_min": "Race 7"}]',
  'numeric',
  '{"min": 1, "max": 25}'
),
(
  3, 1,
  CURRENT_DATE + 2,
  'Read the previous line',
  'pattern',
  2,
  '["Each term in this sequence is built from the one that precedes it. The rule is consistent and uses no arithmetic.", "1,  11,  21,  1211,  111221,  312211,  ?", "What is the next term?"]',
  '13112221',
  '13112221',
  '["The sequence has nothing to do with addition or multiplication. Read each line aloud.", "Describe the previous line out loud: ''one 1'' becomes 11. ''two 1s'' becomes 21.", "Look at 312211. Say what you see: ''one 3, one 1, two 2s, two 1s.''"]',
  'This is the look-and-say sequence, coined by mathematician John Conway. Each term is generated by reading the previous term aloud and encoding what you see.

Most solvers try to find a numerical pattern and miss the trick entirely. The "no arithmetic" hint is the nudge — this is linguistic, not mathematical.',
  '[{"body": "312211 reads as: one 3 → ''13'', one 1 → ''11'', two 2s → ''22'', two 1s → ''21''.", "elapsed_min": "Step 1"}, {"body": "Concatenate: 13 + 11 + 22 + 21 = 13112221.", "elapsed_min": "Step 2"}]',
  'freetext',
  NULL
);
